Add distribution to Java Setup Action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,31 +1,75 @@
-name: Upload to deploygate
+name: build
  
 on:
-  push:
+  pull_request:
     branches:
-    - main
+      - main
 
   workflow_dispatch:
 
 jobs:
-  build:
+  setup:
     runs-on: macos-11
 
     steps:
       - name: Checkout
         uses: actions/checkout@v2
 
+  build:
+    runs-on: macos-11
+
+    needs: setup
+
+    strategy:
+      matrix:
+        node-version: [12.x, 14.x, 16.x]
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Get yarn cache directory path
+        id: yarn-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+
+      - uses: actions/cache@v2
+        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
+        with:
+          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
+      
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+          architecture: x64
+
+      - name: Install node modules
+        run: yarn install
+
+      - name: Test
+        run: yarn test
+
+  build-ios:
+    runs-on: macos-11
+
+    needs: build
+
+    strategy:
+      matrix:
+        node-version: [12.x, 14.x, 16.x]
+
+    steps:
       - name: Set Xcode version
-        run: sudo xcode-select -s "/Applications/Xcode_12.5.1.app"
+        run: sudo xcode-select -s "/Applications/Xcode_13.0.app"
+
       - name: Show Xcode version
         run: xcodebuild -version
 
-      - name: set up JDK 11
-        uses: actions/setup-java@v2.3.1
-        with:
-          java-version: 11
-      
       - name: Import iOS CodeSign Certificates
+        if: github.actor != 'dependabot[bot]'
         uses: Apple-Actions/import-codesign-certs@v1
         id: develop-certificate
         with:
@@ -33,6 +77,7 @@ jobs:
           p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
 
       - name: Import iOS CodeSign Certificates (for distibution)
+        if: github.actor != 'dependabot[bot]'
         uses: Apple-Actions/import-codesign-certs@v1
         with:
           create-keychain: false
@@ -40,13 +85,8 @@ jobs:
           p12-file-base64: ${{ secrets.DISTRIBUTION_CERTIFICATES_FILE_BASE64 }}
           p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
 
-      - name: Import Android CodeSign Certificates
-        run: |
-          ANDROID_CERTIFICATES_FILE_PATH=$(pwd)/android/keystore.p12
-          echo "ANDROID_CERTIFICATES_FILE_PATH=${ANDROID_CERTIFICATES_FILE_PATH}" >> $GITHUB_ENV
-          echo ${{ secrets.ANDROID_CERTIFICATES_FILE_BASE64 }} | base64 -D -o ${ANDROID_CERTIFICATES_FILE_PATH}
-
       - name: Download Provisioning Profiles
+        if: github.actor != 'dependabot[bot]'
         uses: poad/apple-provisioning-profiles-downloader@v1.0.0
         with: 
           bundle-id: 'com.github.poad.*'
@@ -56,51 +96,17 @@ jobs:
           api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
 
       - name: Download Provisioning Profiles (for distibution)
+        if: github.actor != 'dependabot[bot]'
         uses: poad/apple-provisioning-profiles-downloader@v1.0.0
         with: 
           bundle-id: 'com.github.poad.*'
-          profile-type: 'IOS_APP_ADHOC'
+          profile-type: IOS_APP_ADHOC
           issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
           api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
           api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
 
-      - name: Use Node.js ${{ matrix.node-version }}
-        uses: actions/setup-node@v1
-        with:
-          node-version: ${{ matrix.node-version }}
-
-      - name: Configure Homebrew cache
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/Library/Caches/Homebrew/foo--*
-            ~/Library/Caches/Homebrew/downloads/*--foo-*
-          key: brew-${{ hashFiles('.github/brew-formulae') }}
-          restore-keys: brew-
-
-      - name: Add '--no-document' to gemrc
-        run: |
-          echo "install: --no-document" >> ~/.gemrc
-          echo "update: --no-document" >> ~/.gemrc
-          
-      - name: Install and update Homebrew
-        run: |
-          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-          brew update --preinstall
-          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/watchman.rb" > .github/brew-formulae
-          sudo rm '/usr/local/bin/2to3'
-          brew link --overwrite python@3.9
-          brew upgrade
-
-      - name: Setup watchman
-        env:
-          HOMEBREW_NO_AUTO_UPDATE: 1
-        run: |
-          brew install watchman
-          sudo gem update
-
-      - name: Install node modules
-        run: yarn install
+      - name: Checkout
+        uses: actions/checkout@v2
 
       - name: "#️⃣ Update Build Number"
         id: buildnumber
@@ -118,19 +124,61 @@ jobs:
           cat exportOptions.plist.template | sed -e s/\$\{PROVISONING_PROFILE_UUID\}/${PROVISONING_PROFILE_UUID}/g | sed -e s/\$\{TEAM_ID\}/${TEAM_ID}/g >> ios/exportOptions.plist
           cat ios/exportOptions.plist
 
-      - name: Test
-        run: yarn test
+      - name: Get yarn cache directory path
+        id: yarn-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
 
-      - name: Build for android
-        env:
-          ORG_GRADLE_PROJECT_storeFile: ${{ env.ANDROID_CERTIFICATES_FILE_PATH }}
-          ORG_GRADLE_PROJECT_storePassword: ${{ secrets.ANDROID_CERTIFICATES_PASSWORD }}
-          ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_CERTIFICATES_PASSWORD }}
-          ORG_GRADLE_PROJECT_keyAlias: debug
+      - uses: actions/cache@v2
+        id: yarn-cache
+        with:
+          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
+      
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+          architecture: x64
+
+      - name: Install node modules
+        run: yarn install
+
+      - name: Configure Homebrew cache
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/Library/Caches/Homebrew/foo--*
+            ~/Library/Caches/Homebrew/downloads/*--foo-*
+          key: brew-${{ hashFiles('.github/brew-formulae') }}
+          restore-keys: brew-
+
+      - name: Add '--no-document' to gemrc
         run: |
-          ls ${ORG_GRADLE_PROJECT_storeFile}
-          cd android
-          ./gradlew assembleRelease
+          echo "install: --no-document" >> ~/.gemrc
+          echo "update: --no-document" >> ~/.gemrc
+
+      - name: Update Homebrew
+        run: |
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          brew update --preinstall
+          cat "$(brew --repository)/Library/Taps/homebrew/homebrew-core/Formula/watchman.rb" > .github/brew-formulae
+          sudo rm '/usr/local/bin/2to3'
+          brew link --overwrite python@3.9
+          brew upgrade
+
+      - name: Setup watchman
+        env:
+          HOMEBREW_NO_AUTO_UPDATE: 1
+        run: |
+          brew install watchman
+          sudo gem update
+
+      - uses: ruby/setup-ruby@v1
+        with:
+          ruby-version: 2.6
+          bundler-cache: true
 
       - name: Cache Pods dependencies
         uses: actions/cache@v2
@@ -139,6 +187,14 @@ jobs:
           key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
           restore-keys: |
             ${{ runner.os }}-pods-
+
+      - name: Cache Xcode archive
+        uses: actions/cache@v1
+        with:
+          path: ios/Pods
+          key: ${{ runner.OS }}-archive-cache-${{ hashFiles('**/ios/ReactNativeAppSample.xcarchive') }}
+          restore-keys: |
+            ${{ runner.OS }}-archive-cache-
 
       - name: Cache Xcode archive
         uses: actions/cache@v1
@@ -167,15 +223,6 @@ jobs:
           fi
           echo "ipa_file_path=${ipa_file_path}" >> $GITHUB_ENV
 
-      - name: Lookup APK file
-        run: |
-          apk_file_path=$(pwd)/$(ls ./android/app/build/outputs/apk/release/*.apk)
-          if [ -z ${apk_file_path} ]; then
-            echo "APK file is not found" >2
-            exit 1;
-          fi
-          echo "apk_file_path=${apk_file_path}" >> $GITHUB_ENV
-
       - name: Upload IPA file to DeployGate
         env:
           FILE_PATH: ${{ env.ipa_file_path }}
@@ -189,6 +236,76 @@ jobs:
             echo ${RESULT}
             exit 1;
           fi
+
+  build-android:
+    runs-on: macos-11
+
+    needs: build
+
+    strategy:
+      matrix:
+        node-version: [12.x, 14.x, 16.x]
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+
+      - name: Import Android CodeSign Certificates
+        run: |
+          ANDROID_CERTIFICATES_FILE_PATH=$(pwd)/android/keystore.p12
+          echo "ANDROID_CERTIFICATES_FILE_PATH=${ANDROID_CERTIFICATES_FILE_PATH}" >> $GITHUB_ENV
+          echo ${{ secrets.ANDROID_CERTIFICATES_FILE_BASE64 }} | base64 -D -o ${ANDROID_CERTIFICATES_FILE_PATH}
+
+      - name: Get yarn cache directory path
+        id: yarn-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+
+      - uses: actions/cache@v2
+        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
+        with:
+          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-
+      
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ matrix.node-version }}
+          architecture: x64
+
+      - name: Install node modules
+        run: yarn install
+
+      - uses: actions/cache@v2
+        with:
+          path: |
+            ~/.gradle/caches
+            ~/.gradle/wrapper
+          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
+          restore-keys: |
+            ${{ runner.os }}-gradle-
+
+      - name: set up JDK 11
+        uses: actions/setup-java@v2.3.1
+        with:
+          distribution: 'zulu'
+          java-version: 11
+
+      - name: Build and test for android
+        run: |
+          cd android
+          ./gradlew assembleDebug
+          ./gradlew test
+
+      - name: Lookup APK file
+        run: |
+          apk_file_path=$(pwd)/$(ls ./android/app/build/outputs/apk/release/*.apk)
+          if [ -z ${apk_file_path} ]; then
+            echo "APK file is not found" >2
+            exit 1;
+          fi
+          echo "apk_file_path=${apk_file_path}" >> $GITHUB_ENV
 
       - name: Upload APK file to DeployGate
         env:
