Remove the Workflow for TestFlight uploads (#2)
* Update the iOS target to 12.0

* Remove the Workflow for TestFlight uploads

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,15 +3,12 @@ name: Upload to deploygate
 on:
   push:
     branches:
-    - main 
+    - main
 
 jobs:
   build:
     runs-on: macos-latest
 
-    strategy:
-      matrix:
-        node-version: [14.x]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -23,10 +20,10 @@ jobs:
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Use Node.js 14.x
         uses: actions/setup-node@v1
         with:
-          node-version: ${{ matrix.node-version }}
+          node-version: 14.x
           
       - name: Install and update Homebrew
         run: |
@@ -132,6 +129,7 @@ jobs:
           ORG_GRADLE_PROJECT_keyPassword: ${{ secrets.ANDROID_CERTIFICATES_PASSWORD }}
           ORG_GRADLE_PROJECT_keyAlias: debug
         run: |
+          ls ${ORG_GRADLE_PROJECT_storeFile}
           cd android
           ./gradlew assembleRelease
 
@@ -152,7 +150,22 @@ jobs:
           xcodebuild -exportArchive -archivePath ./ReactNativeAppSample.xcarchive -exportPath . -exportOptionsPlist exportOptions.plist
 
       - name: Lookup IPA file
-        run: echo "ipa_file_path=$(pwd)/$(ls ./flutter_app_example/ios/build/*.ipa)" >> $GITHUB_ENV
+        run: |
+          ipa_file_path=$(pwd)/$(ls ./ios/*.ipa)
+          if [ -z ${ipa_file_path} ]; then
+            echo "IPA file is not found" >2
+            exit 1;
+          fi
+          echo "ipa_file_path=${ipa_file_path}" >> $GITHUB_ENV
+
+      - name: Lookup APK file
+        run: |
+          apk_file_path=$(pwd)/$(ls ./android/app/build/outputs/apk/release/*.apk)
+          if [ -z ${apk_file_path} ]; then
+            echo "APK file is not found" >2
+            exit 1;
+          fi
+          echo "apk_file_path=${apk_file_path}" >> $GITHUB_ENV
 
       - name: Upload IPA file to DeployGate
         env:
@@ -163,13 +176,10 @@ jobs:
             -F "file=@${FILE_PATH}" \
             "https://deploygate.com/api/users/poad/apps")
           ERR=$(echo ${RESULT} | jq -c ".error")
-          if [ "${ERR}" = "true"; then
+          if [ "${ERR}" = "true" ]; then
             echo ${RESULT}
             exit 1;
           fi
-
-      - name: Lookup APK file
-        run: echo "apk_file_path=$(ls $(pwd)/flutter_app_example/build/app/outputs/apk/release/*.apk)" >> $GITHUB_ENV
 
       - name: Upload APK file to DeployGate
         env:
